---
- stat:
    path: "{{ x_sddm_conf_file }}"
  register: t_x_sddm_conf_stat

- name: deploy sddm.conf
  template:
    src: sddm/sddm.conf
    dest: "{{ x_sddm_conf_file }}"
    mode: 0644
    owner: root
    group: root
  when: t_x_sddm_conf_stat.stat.exists
