---
- stat:
    path: "{{ sddm_conf_file }}"
  register: t_sddm_conf_stat

- name: deploy sddm.conf
  template:
    src: sddm/sddm.conf
    dest: "{{ sddm_conf_file }}"
    mode: 0644
    owner: root
    group: root
  when: t_sddm_conf_stat.stat.exists
